import type { Dish } from './types';

export const featuredDishes: Dish[] = [
  {
    id: '1',
    name: 'Citrus Glazed Salmon',
    description: 'Perfectly seared salmon with a tangy citrus glaze, served with asparagus.',
    price: 22.5,
    imageUrl: 'https://placehold.co/400x400.png',
    aiHint: 'salmon dish',
    category: 'Food',
  },
  {
    id: '2',
    name: 'Spicy Mango Tango Salad',
    description: 'A vibrant mix of fresh greens, mango, avocado, and a spicy lime dressing.',
    price: 14.0,
    imageUrl: 'https://placehold.co/400x400.png',
    aiHint: 'mango salad',
    category: 'Food',
  },
  {
    id: '3',
    name: 'Herb Infused Risotto',
    description: 'Creamy Arborio risotto infused with fresh herbs and parmesan cheese.',
    price: 18.0,
    imageUrl: 'https://placehold.co/400x400.png',
    aiHint: 'risotto dish',
    category: 'Food',
  },
  {
    id: '7',
    name: 'Passionfruit Sparkler',
    description: 'A refreshing mocktail with passionfruit, mint, and a splash of soda.',
    price: 8.0,
    imageUrl: 'https://placehold.co/400x400.png',
    aiHint: 'fruit drink',
    category: 'Drink',
  }
];

export const menuItems: Dish[] = [
  {
    id: '1',
    name: 'Citrus Glazed Salmon',
    description: 'Perfectly seared salmon with a tangy citrus glaze, served with asparagus.',
    price: 22.5,
    imageUrl: 'https://placehold.co/400x300.png',
    aiHint: 'salmon dish',
    category: 'Food',
  },
  {
    id: '2',
    name: 'Spicy Mango Tango Salad',
    description: 'A vibrant mix of fresh greens, mango, avocado, and a spicy lime dressing.',
    price: 14.0,
    imageUrl: 'https://placehold.co/400x300.png',
    aiHint: 'mango salad',
    category: 'Food',
  },
  {
    id: '3',
    name: 'Herb Infused Risotto',
    description: 'Creamy Arborio risotto infused with fresh herbs and parmesan cheese.',
    price: 18.0,
    imageUrl: 'https://placehold.co/400x300.png',
    aiHint: 'risotto dish',
    category: 'Food',
  },
  {
    id: '4',
    name: 'Zesty Lemon Tart',
    description: 'A classic lemon tart with a buttery crust and a sweet, tangy filling.',
    price: 9.5,
    imageUrl: 'https://placehold.co/400x300.png',
    aiHint: 'lemon tart',
    category: 'Food',
  },
  {
    id: '5',
    name: 'Avocado Toast Deluxe',
    description: 'Sourdough toast topped with smashed avocado, feta, and a sprinkle of chili flakes.',
    price: 12.0,
    imageUrl: 'https://placehold.co/400x300.png',
    aiHint: 'avocado toast',
    category: 'Food',
  },
  {
    id: '6',
    name: 'Mushroom & Truffle Pizza',
    description: 'Artisanal pizza with a creamy truffle sauce, mixed mushrooms, and mozzarella.',
    price: 20.0,
    imageUrl: 'https://placehold.co/400x300.png',
    aiHint: 'mushroom pizza',
    category: 'Food',
  },
  {
    id: '7',
    name: 'Passionfruit Sparkler',
    description: 'A refreshing mocktail with passionfruit, mint, and a splash of soda.',
    price: 8.0,
    imageUrl: 'https://placehold.co/400x300.png',
    aiHint: 'fruit drink',
    category: 'Drink',
  },
  {
    id: '8',
    name: 'Cold Brew Coffee',
    description: 'Smooth, rich cold brew coffee, steeped for 12 hours for a less acidic taste.',
    price: 5.5,
    imageUrl: 'https://placehold.co/400x300.png',
    aiHint: 'cold coffee',
    category: 'Drink',
  },
  {
    id: '9',
    name: 'Berry Bliss Smoothie',
    description: 'A blend of mixed berries, banana, yogurt, and a hint of honey.',
    price: 9.0,
    imageUrl: 'https://placehold.co/400x300.png',
    aiHint: 'berry smoothie',
    category: 'Drink',
  },
];
